# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json
# Version file (schema 1.12.0)
# Part of a 3-file multi-file manifest set for winget-pkgs.

PackageIdentifier: eddyuk.NumPaDeck
PackageVersion: 1.0.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
